version: 1.0.{build}

image: Visual Studio 2017
configuration: Release
platform: Any CPU

environment:
  webapp_folder: .\almtestet2
  webapp_proj: $(webapp_folder)\almtestet2.csproj
  webapp_package: almtestet2.$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)
  test_proj: .\UnitTestProject1\UnitTestProject1.csproj

before_build:
  - ps: dotnet restore

build:
  verbosity: minimal
  project: almtestet2.sln

after_build:
  - ps: .\package.ps1 -projectPath $env:webapp_proj -packageName $env:webapp_package -absoluteRepoDirectory $env:APPVEYOR_BUILD_FOLDER

artifacts:
  - path: '**\$(webapp_package).zip'


  